### ISSUE TITLE
Does not support M2E

### ISSUE THREAD

**Issue by gengu** [sundrio/sundrio#124]
```
When I import to Eclipse，I can see log 

!ENTRY org.eclipse.core.resources 4 2 2019-01-21 16:14:36.990
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
io.sundr.shaded.org.apache.velocity.exception.VelocityException: Error initializing log: Failed to initialize an instance of io.sundr.shaded.org.apache.velocity.runtime.log.NullLogChute with the current runtime configuration.
        at io.sundr.shaded.org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:875)
        at io.sundr.shaded.org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:262)
        at io.sundr.shaded.org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:93)
        at io.sundr.codegen.generator.CodeGeneratorContext.<init>(CodeGeneratorContext.java:56)
        at io.sundr.codegen.generator.CodeGeneratorContext.<init>(CodeGeneratorContext.java:41)
        at io.sundr.codegen.processor.JavaGeneratingProcessor.<init>(JavaGeneratingProcessor.java:40)
        at io.sundr.builder.internal.processor.AbstractBuilderProcessor.<init>(AbstractBuilderProcessor.java:51)
        at io.sundr.builder.internal.processor.BuildableProcessor.<init>(BuildableProcessor.java:49)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.eclipse.jdt.apt.core.internal.ClassServiceFactory.newInstance(ClassServiceFactory.java:30)
        at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.discoverNextProcessor(IdeAnnotationProcessorManager.java:96)
        at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:119)
        at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:162)
        at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
        at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:264)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:182)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:834)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:271)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:324)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:327)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:379)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:400)
        at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:504)
        at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:404)
        at org.eclipse.jdt.ls.core.internal.handlers.BuildWorkspaceHandler.buildWorkspace(BuildWorkspaceHandler.java:64)
        at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$24(JDTLanguageServer.java:714)
        at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:764)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.sundr.shaded.org.apache.velocity.exception.VelocityException: Failed to initialize an instance of io.sundr.shaded.org.apache.velocity.runtime.log.NullLogChute with the current runtime configuration.
        at io.sundr.shaded.org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:220)
        at io.sundr.shaded.org.apache.velocity.runtime.log.LogManager.updateLog(LogManager.java:269)
        at io.sundr.shaded.org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:871)
        ... 47 more
Caused by: io.sundr.shaded.org.apache.velocity.exception.VelocityException: The specified logger class io.sundr.shaded.org.apache.velocity.runtime.log.NullLogChute does not implement the io.sundr.shaded.org.apache.velocity.runtime.log.LogChute interface.
        at io.sundr.shaded.org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:181)
        ... 49 more

```

**Comment by iocanel** [comment]
Hi @gengu! Can you please let me know which version you are using?

I was having the same issue myslelf when using the eclipse language server but it was fixed as of: https://github.com/sundrio/sundrio/commit/66936de39f5cb4cb6fff0dd16b51f0459e9520d3

So, in the latest master and 0.14.5 onward it should be fixed.

**Comment by ydewit** [comment]
We are seeing the same issue after importing https://github.com/kubernetes-client/java master branch into Eclipse.

There, `client-java-api` depends on `builder-annotations`, which in turn depends on sundr.core and sundr.codegen version 0.9.2.

Upgrading to 0.14.5 seems to be causing other code generation problems there in `kubernetes-client/java`.

**Comment by iocanel** [comment]
@ydewit: can you please let me know about the other code generation problems you have?

**Comment by ydewit** [comment]
I tried building kubernetes-client with the latest sundrio version 0.18.0, but got the following errors (tests disabled):
```
java.lang.IllegalStateException: Calc manifest failed
...
    at aQute.bnd.osgi.Analyzer.calcManifest (Analyzer.java:901)
    at aQute.bnd.osgi.Builder.build (Builder.java:108)
    at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle (BundlePlugin.java:972)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:467)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:384)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:375)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.nio.file.NoSuchFileException: /tmp/kubernetes-client/java/kubernetes/target/classes/io/kubernetes/client/models/V1ObjectMetaFluent.class
    at sun.nio.fs.UnixException.translateToIOException (UnixException.java:92)
    at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:111)
    at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:116)
    at sun.nio.fs.UnixFileSystemProvider.newFileChannel (UnixFileSystemProvider.java:178)
    at java.nio.channels.FileChannel.open (FileChannel.java:292)
    at aQute.lib.io.IO.readChannel (IO.java:874)
    at aQute.lib.io.IO.read (IO.java:464)
    at aQute.bnd.osgi.FileResource.buffer (FileResource.java:66)
    at aQute.bnd.osgi.Clazz.parseClassFileWithCollector (Clazz.java:492)
    at aQute.bnd.osgi.Clazz.parseClassFile (Clazz.java:484)
    at aQute.bnd.osgi.Analyzer.findClass (Analyzer.java:2742)
    at aQute.bnd.osgi.Analyzer.isProvider (Analyzer.java:1827)
    at aQute.bnd.osgi.Analyzer.findProvidedPackages (Analyzer.java:1818)
    at aQute.bnd.osgi.Analyzer.augmentImports (Analyzer.java:1673)
    at aQute.bnd.osgi.Analyzer.analyze (Analyzer.java:305)
    at aQute.bnd.osgi.Builder.analyze (Builder.java:387)
    at aQute.bnd.osgi.Analyzer.calcManifest (Analyzer.java:694)
    at aQute.bnd.osgi.Builder.build (Builder.java:108)
    at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle (BundlePlugin.java:972)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:467)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:384)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:375)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
```
It seems to be a TODO on kubernetes-client/java to migrate to the latest version of sundrio. Are there generate file name changes?

**Comment by iocanel** [comment]
@ydewit: Can't think of something taht would break the bundle configuration. 
I'll open the project itself and have a closer look.

**Comment by iocanel** [comment]
@ydewit: It works ok for me, infact I sent a pull request to upgrade the issue.

I am closing this one as its fixed.
