### ISSUE TITLE
Suspected regression in 0.101.2 - VisitableMap.get(Object) is null affecting with methods with Optionals

### ISSUE THREAD

**Issue by k-wall** [sundrio/sundrio#442]
I'm seeing what I believe is a regression on upgrading from 0.101.0 to 0.101.2.   My tests are falling with the following NPE originating from within the sundrio generated code.

```
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "io.kroxylicious.proxy.config.VisitableMap.get(Object)" is null

	at io.kroxylicious.proxy.config.TargetClusterFluent.withTls(TargetClusterFluent.java:50)
	at io.kroxylicious.proxy.config.TargetClusterFluent.copyInstance(TargetClusterFluent.java:28)
	at io.kroxylicious.proxy.config.TargetClusterBuilder.<init>(TargetClusterBuilder.java:19)
	at io.kroxylicious.proxy.config.VirtualClusterFluent.withTargetCluster(VirtualClusterFluent.java:48)
	at io.kroxylicious.proxy.config.VirtualClusterFluent$TargetClusterNested.and(VirtualClusterFluent.java:209)
	at io.kroxylicious.proxy.config.VirtualClusterFluent$TargetClusterNested.endTargetCluster(VirtualClusterFluent.java:213)
	at io.kroxylicious.proxy.config.ConfigurationTest.fluentApiConfigYamlFidelity(ConfigurationTest.java:114)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
```

It looks like a change in the generated `with` method is the root cause.  Notice that argument to  `_visitables.get()` has been changed like this:

`_visitables.get("tls")` =>  `_visitables.get(tls)`

It used to be a string named after the field (`tls` in my case), but is now the object itself.  I suspect that this is regression in sundrio.    

## 0.101.2 

```
  public A withTls(Optional<Tls> tls) {
    if (tls == null || !tls.isPresent()) {
      this.tls = java.util.Optional.empty();
    } else {
        TlsBuilder b = new TlsBuilder(tls.get());;
        _visitables.get(tls).add(b);
    }
    return (A) this;
  }
```

## 0.101.0

```

  public A withTls(Optional<Tls> tls) {
    if (tls == null || !tls.isPresent()) { this.tls = Optional.empty(); } 
    else {TlsBuilder b = new TlsBuilder(tls.get()); _visitables.get("tls").add(b); this.tls = Optional.of(b); } return (A) this;
  }
```

**Comment by iocanel** [comment]
@k-wall Thank you so much for the quality feedback. Will have a look asap.

**Comment by k-wall** [comment]
I confirm that 0.101.3 addresses the issue.  Thank you.
