### ISSUE TITLE
`index out of bounds` error when using Sundrio generated builder with version 0.101.1 and newer

### ISSUE THREAD

**Issue by scholzj** [sundrio/sundrio#471]
In the Strimzi project, I tried to upgrade Sundrio from 0.100.3 to 0.103.1. But one of the builders we use for the Kubernetes Custom Resource objects started to fail with `java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0` error. It seems to happen when we in the same builder mix `edit*` methods with `with*` methods. It looks like it resets some internal state in the builder and loses some information which causes the exception.

I created a stripped-down reproducer that should hopefully help to better explain the bug. It is in https://github.com/scholzj/sundrio-index-out-of-bound

It has some classes used to generate the builders in https://github.com/scholzj/sundrio-index-out-of-bounds/tree/main/src/main/java/io/strimzi/api/kafka/model/mirrormaker2. And it has a simple unit test that shows what fails: https://github.com/scholzj/sundrio-index-out-of-bounds/blob/main/src/test/java/io/strimzi/api/kafka/model/mirrormaker2/KafkaMirrorMaker2Test.java

* The `testFailingBuilder` test is failing with Sundri 0.101.1 and higher and passing with Sundrio 0.101.0 and older
* The `testSucceedingBuilder` seems to always work
* The difference between the tests is in these three lines: https://github.com/scholzj/sundrio-index-out-of-bounds/blob/main/src/test/java/io/strimzi/api/kafka/model/mirrormaker2/KafkaMirrorMaker2Test.java#L94-L96
  When the `withNewInlineLogging` is used, the `endMirror` throws the exception:
  ```
  java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
  
	  at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	  at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	  at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	  at java.base/java.util.Objects.checkIndex(Objects.java:361)
	  at java.base/java.util.ArrayList.set(ArrayList.java:441)
	  at io.strimzi.api.kafka.model.mirrormaker2.KafkaMirrorMaker2SpecFluent.setToMirrors(KafkaMirrorMaker2SpecFluent.java:260)
	  at io.strimzi.api.kafka.model.mirrormaker2.KafkaMirrorMaker2SpecFluent$MirrorsNested.and(KafkaMirrorMaker2SpecFluent.java:494)
	  at io.strimzi.api.kafka.model.mirrormaker2.KafkaMirrorMaker2SpecFluent$MirrorsNested.endMirror(KafkaMirrorMaker2SpecFluent.java:498)
	  at io.strimzi.api.kafka.model.mirrormaker2.KafkaMirrorMaker2Test.testFailingBuilder(KafkaMirrorMaker2Test.java:55)
  ```
  When it is commented out, the test will pass.

Any idea what might be the problem? Thanks!

**Comment by iocanel** [comment]
Thanks for the reproducer. Looking at it.

**Comment by scholzj** [comment]
Thanks for looking into it and fixing it.
